### ISSUE TITLE
Example of YML NPM Publish

### ISSUE THREAD

**Issue by manico** [actions/npm#38]
It seems there is no examples to be found on how to publish npm package while setting secret npm auth and filtering only for tags. Could you provide an example?

**Comment by manico** [comment]
Found a way, but don't know how to publish only if tag is present.
Currently it fails if there is no tag.

```
name: Build and Publish Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: NPM Build and Test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: Publish
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish
```

**Comment by run1t** [comment]
First thanks for the `.yml`.
I was able to trigger `tags` change with : 
```yml
name: Release

on:
  push:
    tags:
      - '*'
```

Don't if this is the best method but it works 😃
