### ISSUE TITLE
Add support for Windows environments

### ISSUE THREAD

**Issue by qJake** [actions/npm#39]
## Description

Action is not available for Windows-based actions.

## Symptom

Running the action on a Windows environment yields the following error:

> ##[error]Container action is only supported on Linux

## Steps to Reproduce

Create an action similar to the following:

```yaml
name: Sample NPM CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
        
    - name: Setup NPM
      uses: actions/npm@v2.0.0
      
    - name: npm install
      run: npm install
```

## Desired Outcome

NPM should be available in Windows and should add itself for future step commands such as `npm install`.
